import SideBar from "./componnets/layouts/SideBar";
import "./globals.css";
import "./styles/dashboard.css";
import type { Metadata } from "next";
import { Content, Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Instagram",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="w-screen h-full min-h-screen flex">
          <SideBar />
          <div className="w867 bg-white flex pt-[22px] items-center justify-center min-w-0">
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
